spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jobs
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 5000

